const uiPreset = require('./preset/preset')

module.exports = {
  darkMode: 'class',
  presets: [require('@medusajs/ui-preset'), uiPreset],
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/modules/**/*.{js,ts,jsx,tsx}',
    './node_modules/@medusajs/ui/dist/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['var(--font-inter)', 'Inter', 'sans-serif'],
        body:     ['var(--font-inter)', 'Inter', 'sans-serif'],
        label:    ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      // Explicit overrides for bg-*/text-*/border-* — the local preset's
    // backgroundColor/textColor/borderColor sections use CSS variables
    // (--bg-primary = white, --content-secondary = dark) which would
    // otherwise win over our colors.* entries for those same keys.
    backgroundColor: {
      primary:   '#006875',
      secondary: '#5d5e61',
      error:     '#ba1a1a',
    },
    textColor: {
      primary:   '#006875',
      secondary: '#5d5e61',
      'on-primary':   '#ffffff',
      'on-secondary': '#ffffff',
    },
    borderColor: {
      primary:   '#006875',
      secondary: '#5d5e61',
    },
    colors: {
        primary:                    '#006875',
        'on-primary':               '#ffffff',
        'primary-container':        '#00e5ff',
        'primary-fixed':            '#9cf0ff',
        'primary-fixed-dim':        '#00daf3',
        'on-primary-fixed':         '#001f24',
        'on-primary-fixed-variant': '#004f58',
        'on-primary-container':     '#00626e',
        'inverse-primary':          '#00daf3',
        secondary:                  '#5d5e61',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#e2e2e5',
        'on-secondary-container':   '#636467',
        'secondary-fixed':          '#e2e2e5',
        'secondary-fixed-dim':      '#c6c6c9',
        'on-secondary-fixed':       '#1a1c1e',
        'on-secondary-fixed-variant':'#454749',
        tertiary:                   '#5a5f66',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#ccd1d9',
        'on-tertiary-container':    '#545961',
        'tertiary-fixed':           '#dee3eb',
        'tertiary-fixed-dim':       '#c2c7cf',
        'on-tertiary-fixed':        '#171c22',
        'on-tertiary-fixed-variant':'#42474e',
        surface:                    '#f8f9fa',
        'surface-dim':              '#d9dadb',
        'surface-bright':           '#f8f9fa',
        'surface-variant':          '#e1e3e4',
        'surface-tint':             '#006875',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f3f4f5',
        'surface-container':        '#edeeef',
        'surface-container-high':   '#e7e8e9',
        'surface-container-highest':'#e1e3e4',
        'on-surface':               '#191c1d',
        'on-surface-variant':       '#3b494c',
        'on-background':            '#191c1d',
        background:                 '#f8f9fa',
        'inverse-surface':          '#2e3132',
        'inverse-on-surface':       '#f0f1f2',
        outline:                    '#6b7a7d',
        'outline-variant':          '#bac9cc',
        error:                      '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      transitionProperty: {
        width: 'width margin',
        height: 'height',
        bg: 'background-color',
        display: 'display opacity',
        visibility: 'visibility',
        padding: 'padding-top padding-right padding-bottom padding-left',
      },
      keyframes: {
        ring: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        'fade-in-right': { '0%': { opacity: '0', transform: 'translateX(10px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        'fade-in-top': { '0%': { opacity: '0', transform: 'translateY(-10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-out-top': { '0%': { height: '100%' }, '99%': { height: '0' }, '100%': { visibility: 'hidden' } },
        'accordion-slide-up': { '0%': { height: 'var(--radix-accordion-content-height)', opacity: '1' }, '100%': { height: '0', opacity: '0' } },
        'accordion-slide-down': { '0%': { 'min-height': '0', 'max-height': '0', opacity: '0' }, '100%': { 'min-height': 'var(--radix-accordion-content-height)', 'max-height': 'none', opacity: '1' } },
        enter: { '0%': { transform: 'scale(0.9)', opacity: 0 }, '100%': { transform: 'scale(1)', opacity: 1 } },
        leave: { '0%': { transform: 'scale(1)', opacity: 1 }, '100%': { transform: 'scale(0.9)', opacity: 0 } },
        'slide-in': { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(0)' } },
      },
      animation: {
        ring: 'ring 2.2s cubic-bezier(0.5, 0, 0.5, 1) infinite',
        'fade-in-right': 'fade-in-right 0.3s cubic-bezier(0.5, 0, 0.5, 1) forwards',
        'fade-in-top': 'fade-in-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards',
        'fade-out-top': 'fade-out-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards',
        'accordion-open': 'accordion-slide-down 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards',
        'accordion-close': 'accordion-slide-up 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards',
        enter: 'enter 200ms ease-out',
        'slide-in': 'slide-in 1.2s cubic-bezier(.41,.73,.51,1.02)',
        leave: 'leave 150ms ease-in forwards',
      },
    },
  },
  plugins: [require('tailwindcss-radix')()],
}
