#!/bin/bash
set -e

# Write env vars to .env.production so vercel build subprocess can read them
cat > .env.production <<EOF
NEXT_PUBLIC_MEDUSA_BACKEND_URL=$NEXT_PUBLIC_MEDUSA_BACKEND_URL
NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=$NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
NEXT_PUBLIC_MINIO_ENDPOINT=$NEXT_PUBLIC_MINIO_ENDPOINT
NEXT_PUBLIC_SEARCH_API_KEY=$NEXT_PUBLIC_SEARCH_API_KEY
NEXT_PUBLIC_SEARCH_ENDPOINT=$NEXT_PUBLIC_SEARCH_ENDPOINT
NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
EOF

echo ".env.production written:"
for key in NEXT_PUBLIC_MEDUSA_BACKEND_URL NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY NEXT_PUBLIC_MINIO_ENDPOINT NEXT_PUBLIC_SEARCH_API_KEY NEXT_PUBLIC_SEARCH_ENDPOINT NEXT_PUBLIC_BASE_URL; do
  val=$(printenv "$key" || true)
  [ -n "$val" ] && echo "  $key: SET" || echo "  $key: NOT SET"
done

pnpm exec next-on-pages
